config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  devise_for :users
  resources :movies
  resources :cines
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cine.rb
class Cine < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :cine
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
    end 
end

app/controllers/cines_controller.rb
class CinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cine, only: [:show, :edit, :update, :destroy]

  # GET /cines
  # GET /cines.json
  def index
    @cines = Cine.all
  end

  # GET /cines/1
  # GET /cines/1.json
  def show
    @movies = Movie.where cine_id: @cine.id
  end

  # GET /cines/new
  def new
    @cine = Cine.new
  end

  # GET /cines/1/edit
  def edit
  end

  # POST /cines
  # POST /cines.json
  def create
    @cine = Cine.new(cine_params)

    respond_to do |format|
      if @cine.save
        format.html { redirect_to @cine, notice: 'Cine was successfully created.' }
        format.json { render :show, status: :created, location: @cine }
      else
        format.html { render :new }
        format.json { render json: @cine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cines/1
  # PATCH/PUT /cines/1.json
  def update
    respond_to do |format|
      if @cine.update(cine_params)
        format.html { redirect_to @cine, notice: 'Cine was successfully updated.' }
        format.json { render :show, status: :ok, location: @cine }
      else
        format.html { render :edit }
        format.json { render json: @cine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cines/1
  # DELETE /cines/1.json
  def destroy
    @cine.destroy
    respond_to do |format|
      format.html { redirect_to cines_url, notice: 'Cine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cine
      @cine = Cine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cine_params
      params.require(:cine).permit(:name, :phone, :url_image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @catalogue = Movie.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @cines = Cine.all
  end

  # GET /movies/1/edit
  def edit
    @cines = Cine.all
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :duration, :date_time_movie, :cine_id, :url_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cines_helper.rb
module CinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/cines/_form.html.erb
<div class="container is-fluid">
    <div style="width:300px">
        <%= form_with(model: cine, local: true) do |form| %>
        <% if cine.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(cine.errors.count, "error") %> prohibited this cine from being saved:</h2>

            <ul>
                <% cine.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul> 
        </div>
        <% end %>

        <div class="field">
            <%= form.label :name, class: "label"%>
            <div class="control">
                <%= form.text_field :name, class: "input" %>
            </div>
        </div>

        <div class="field">
            <%= form.label :phone, class: "label" %>
            <div class = "control">
              <%= form.number_field :phone, class: "input", max: "99999999", min:"10000000" %> <!-- Solucion rapida para que no rompa la aplicacion -->
            </div>
        </div>

        <div class="field">
            <%= form.label :url_image, class: "label" %>
            <div class = "control">
              <%= form.text_field :url_image, class: "input" %>
            </div>
        </div>

        <div class="actions control">
            <%= form.submit %>
        </div>
        <% end %>

    </div>
</div>

app/views/cines/edit.html.erb
<div class="container is-fluid">
    <h1 class="title">Editing Cine</h1>
</div>

<%= render 'form', cine: @cine %>

<div class="container is-fluid mt-2">
    <div class="field is-grouped">
        <p class="control">
            <%= link_to '<i class="fas fa-arrow-left"></i> Back'.html_safe, cines_path, class: "button is-text" %>
        </p>
        
        <p class="control">
            <%= link_to '<i class="far fa-eye"></i> Show'.html_safe, @cine, class: "button is-text" %> 
        </p>
    </div>
</div>

app/views/cines/index.html.erb
<div class="container is-fluid mb-1" style="display:flex; justify-content:space-between">
  <h1 class="title">Cines</h1>
  <a href="<%= new_cine_path %>" class="button is-success is-outlined"><i class="fas fa-plus mr-1"></i> New </a>
</div>
 
<div class="container is-fluid">
    <% @cines.each do |cine| %>
      <div class="mb-2 has-background-light is-relative py-2 px-2 animar">

        <a href="/cines/<%= cine.id %>" style="display:flex">
          <img src="<%= cine.url_image %>" class="image is-128x128">
          
          <div class="ml-2 has-text-dark">
            <h2 class="subtitle mb-0"><%= cine.name %></h2>
            <span ><strong>Phone: </strong><%= cine.phone %></span>
          </div>
        </a>
        <div class="ml-5 mb-0 buttons" style="position:absolute; left:120px; bottom:0; z-index:100000">
          <a href="<%= edit_cine_path(cine) %>" class="button is-link is-outlined"> <i class="fas fa-pen mr-1"></i> Edit </a>
          <%= link_to "<i class='fas fa-trash-alt mr-1'></i> Delete".html_safe, cine , method: :delete, data: { confirm: '¿Eliminar Cine?' }, class: "button is-danger is-outlined" %>
        </div>
      </div>
    <% end %>
</div>


app/views/cines/new.html.erb
<div class="container is-fluid">
    <h1 class="title">New Cine</h1>
</div>
<%= render 'form', cine: @cine %>

<div class="container is-fluid mt-2">
    <div class="field is-grouped">
        <p class="control">
            <%= link_to '<i class="fas fa-arrow-left"></i> Back'.html_safe, cines_path, class: "button is-text" %>
        </p>
    </div>
</div>

app/views/cines/show.html.erb
<div class="container is-fluid mb-1" style="display:flex; justify-content:space-between">
  <a href=" <%= cines_path %>" class= "button is-text"> <i class="fas fa-arrow-left"></i> Back </a>
  <div style="display:flex; aling-item:center">
      <img src="<%= @cine.url_image %>" class="image is-96x96">
    <div class="ml-2">
      <h1 class="title mb-0"><%= @cine.name %></h1>
      <p class="ml-1"><strong>phone:</strong> <%= @cine.phone %></p>
    </div>
  </div>
  <a href="<%= edit_cine_path(@cine) %>" class="button is-text"> <i class="fas fa-pen"></i> Edit </a>
</div>

<div class="container is-fluid mt-6" style="display:flex; justify-content:space-between">
  <h2 class="title">Available Movies</h2>
</div>

<div class="container is-fluid mt-2">
  <% @movies.each do |movie| %>
    <div class="mb-2 has-background-light is-relative py-2 px-2 animar" style="border-radius:5px">

      <a href="/movies/<%= movie.id %>" class="" style="display:flex">

        <img src="<%= movie.url_image %>" style="width: 120px">
        
        <div class="ml-2 has-text-dark">
          <h2 class="subtitle"><%= movie.name %></h2>

          <span class="card__data__container__datetime">
            <%= I18n.l(movie.date_time_movie, format: '%A, %d de %B de %Y') %> |
            <%= movie.date_time_movie.strftime("%H:%M") %>
          </span>
          <br>
          
          
          <span class="card__data__container__duration">
            <strong>Duration: </strong>
            <%= movie.duration.strftime("%H:%M") %>
          </span>

          <span class="card__data__container__cine">
            <strong>In: </strong>
            <%= movie.cine.name %>
          </span>
        </div>
      </a>
      <div class="ml-4 mb-2 buttons" style="position:absolute; left:120px; bottom:0; z-index:100000">
        <a href="<%= edit_movie_path(movie) %>" class="button is-link is-outlined"> <i class="fas fa-pen mr-1"></i> Edit <a>
        <%= link_to "<i class='fas fa-trash-alt mr-1'></i> Delete".html_safe, movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-danger is-outlined" %>
      </div>
    </div>    
  <% end %>
</div>  

app/views/home/index.html.erb
<div class="container is-fluid mb-1" style="display:flex; justify-content:space-between">
  <h1 class="title">Catalogo</h1>
</div>

<div class="container is-fluid">
    <% @catalogue.each do |movie| %>
      <div class="mb-2 has-background-light is-relative py-2 px-2 animar" style="border-radius:5px">

        <a href="/movies/<%= movie.id %>" style="display:flex">

          <img src="<%= movie.url_image %>" style="width: 120px; height: 180px">
          
          <div class="ml-2 has-text-dark">
            <h2 class="subtitle"><%= movie.name %></h2>

            <span class="card__data__container__datetime">
              <%= I18n.l(movie.date_time_movie, format: '%A, %d de %B de %Y') %> |
              <%= movie.date_time_movie.strftime("%H:%M") %>
            </span>
            <br>
            
            
            <span class="card__data__container__duration">
              <strong>Duration: </strong>
              <%= movie.duration.strftime("%H:%M") %>
            </span>

            <span class="card__data__container__cine">
              <strong>In: </strong>
              <%= movie.cine.name %>
            </span>
          </div>
        </a>
      </div>    
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cinema</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CDN de bulma -->   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.css">
    <!-- CDN de fontawesome -->   
    <script src="https://kit.fontawesome.com/65874f9339.js" crossorigin="anonymous"></script>
    <!-- scripts de rails -->   
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- stilos de rails -->   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="<%= root_path %>">
          <%= image_tag 'logo.png' %>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to 'Catalogue', root_path, class: "navbar-item" %>
          <%= link_to 'Cines', cines_path, class: "navbar-item" %>
          <%= link_to 'Movies', movies_path, class: "navbar-item" %> 
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                  <figure class="image is-32x32">
                    <img src="<%= current_user.photo.url %>">
                  </figure>
                  <span style="margin-left: 10px"> <%= current_user.email %> <span>
                </a>
                <div class="navbar-dropdown">
                  <%= link_to 'Edit Profile', edit_user_registration_path, class: "navbar-item" %>
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?'}, class: "navbar-item" %>
                </div>
              </div>
            <% else %>  
              <div class="buttons">
                <a href="<%= new_user_registration_path %>" class="button is-primary">
                  <strong>Sign up</strong>
                </a>
                <a href="<%= new_user_session_path %>" class="button is-light">
                  Log in
                </a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <div>
      <% if notice %>
        <p class="notice notification is-primary is-light" id="notification"><%= notice %></p>
      <% elsif alert %>  
        <p class="alert notification is-danger is-light" id="notification"><%= alert %></p>
      <% end %>   
    <div>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="container is-fluid">
    <div style="width:350px">
        <%= form_with(model: movie, local: true) do |form| %>
        <% if movie.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

            <ul>
                <% movie.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <div class="field">
            <%= form.label :name, class: "label" %>
            <div class="control">
              <%= form.text_field :name, class: "input" %>
            </div>
        </div>

        <div class="field">
            <%= form.label :duration, class: "label" %>
            <div class="control">
              <%= form.time_select :duration, class: "input" %>
            </div>
        </div>

        <div class="field">
            <%= form.label :date_time_movie, class: "label" %>
            <div class="control">
              <%= form.datetime_select :date_time_movie , class: "input" %>
            </div>
        </div>

        <div class="field">
          <%= form.label :cine_id, class: "label" %>
          <div class="control">
            <div class="select">
              <select name="movie[cine_id]" id="movie_cine_id">
                <% @cines.each do |cine| %>
                  <option value="<%= cine.id %>"><%= cine.name %></option>
                <% end %>
              </select>
            </div>
          </div>
        </div>

        <div class="field">
            <%= form.label :url_image, class: "label" %>
            <div class="control">
              <%= form.text_field :url_image, class: "input" %>
            </div>
        </div>

        <div class="actions">
              <%= form.submit %>
        </div>
        <% end %>
    </div>
</div>

app/views/movies/edit.html.erb
<div class="container is-fluid">
    <h1 class="title">Editing Movie</h1>
</div>

<%= render 'form', movie: @movie %>

<div class="container is-fluid  mt-2">
    <div class="field is-grouped">
        <p class="control">
            <%= link_to '<i class="fas fa-arrow-left"></i> Back'.html_safe, movies_path, class: "button is-text" %>
        </p>
        <p class="control">
            <%= link_to '<i class="far fa-eye"></i> Show'.html_safe, @movie, class: "button is-text" %>
        </p>
    </div>
</div>

app/views/movies/index.html.erb
<div class="container is-fluid mb-1" style="display:flex; justify-content:space-between">
  <h1 class="title">Movies</h1>
  <a href="<%= new_movie_path %>" class="button is-success is-outlined"><i class="fas fa-plus mr-1"></i> New </a>
</div>

<div class="container is-fluid">

    <% @movies.each do |movie| %>
      <div class="mb-2 has-background-light is-relative py-2 px-2 animar" style="border-radius:5px">

        <a href="/movies/<%= movie.id %>" style="display:flex">

          <img src="<%= movie.url_image %>" style="width: 120px; height: 180px;">
          
          <div class="ml-2 has-text-dark">
            <h2 class="subtitle"><%= movie.name %></h2>

            <span class="card__data__container__datetime">
              <%= I18n.l(movie.date_time_movie, format: '%A, %d de %B de %Y') %> |
              <%= movie.date_time_movie.strftime("%H:%M") %>
            </span>
            <br>
            
            
            <span class="card__data__container__duration">
              <strong>Duration: </strong>
              <%= movie.duration.strftime("%H:%M") %>
            </span>

            <span class="card__data__container__cine">
              <strong>in: </strong>
              <%= movie.cine.name %>
            </span>
          </div>
        </a>
        <div class="ml-4 mb-2 buttons" style="position:absolute; left:120px; bottom:0; z-index:100000">
          <a href="<%= edit_movie_path(movie) %>" class="button is-link is-outlined"> <i class="fas fa-pen mr-1"></i> Edit </a>
          <%= link_to "<i class='fas fa-trash-alt mr-1'></i> Delete".html_safe, movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-danger is-outlined" %>
        </div>
      </div>    
    <% end %>
  </div>

app/views/movies/new.html.erb
<div class="container is-fluid">
    <h1 class="title">New Movie</h1>
</div>

<%= render 'form', movie: @movie %>

<div class="container is-fluid mt-2">
    <div class="field is-grouped">
        <p class="control">
            <%= link_to '<i class="fas fa-arrow-left"></i> Back'.html_safe, movies_path, class: "button is-text" %>
        </p>
    </div>
</div>

app/views/movies/show.html.erb
<div class="container is-fluid mt-2">
    <img src="<%= @movie.url_image %>" style="width:250px">

    <div>
        <p class="title"> <%= @movie.name %> </p>
        <p> <strong>Duration:</strong> <%= @movie.duration.strftime("%H:%M") %> </p>
        <p><strong>Date time movie:</strong> <%= I18n.l(@movie.date_time_movie, format: '%A, %d de %B de %Y') %> |<%= @movie.date_time_movie.strftime("%H:%M") %></p>
        <p><strong>Cine:</strong> <%= @movie.cine.name %> </p>
    </div>

    <div class="field is-grouped mt-2">
      <p class="control">
        <a href=" <%= movies_path %>" class= "button is-text"> <i class="fas fa-arrow-left"></i> Back <a>
      </p>

      <p class="control">
        <a href="<%= edit_movie_path(@movie) %>" class="button is-text"> <i class="fas fa-pen"></i> Edit <a>
      </p>
    </div>
</div>
